language: android
jdk: oraclejdk8

install: true

before_install:
  - touch local.properties
  - chmod +x ".travis/build.sh"
  - chmod +x "gradlew"
  - chmod +x "gradlew.bat"

android:
 components:
  - tools
  - platform-tools
  - build-tools-27.0.3
  - android-27

script:
  - ".travis/build.sh"

before_cache:
  # remove all the artifacts (JAR, ZIP) that are installed in local repo because of gradle deploy
  - rm -f  $HOME/.gradle/caches/modules-2/modules2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.sonar/cache
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper

licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+